# Generated by Django 3.2.8 on 2021-11-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='thumname_image',
        ),
    ]
