# Generated by Django 3.2.9 on 2021-11-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='thumname_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='email',
            field=models.EmailField(default='ata97@naver.com', max_length=255),
        ),
    ]
