# Generated by Django 3.2.9 on 2021-12-02 11:48

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_photo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('writer', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('cloth_image', models.ImageField(upload_to=main.models.upload_to_func)),
            ],
        ),
    ]
