# Generated by Django 3.2.9 on 2021-12-02 12:19

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_posting_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='cloth_image',
            field=models.ImageField(upload_to=main.models.upload_to_posting),
        ),
        migrations.AlterField(
            model_name='posting',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
