# Generated by Django 3.2.8 on 2021-12-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211122_2041'),
        ('main', '0006_auto_20211202_2119'),
    ]

    operations = [
    ]
