# Generated by Django 3.2.8 on 2021-11-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Not to disclose')], default=2),
        ),
    ]
