# Generated by Django 3.2.8 on 2021-11-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_users_gender'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='User',
            managers=[
            ],
        ),
    ]
